/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fx.frontend;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App  extends Application {


    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        //loader.setControllerFactory(applicationContext::getBean);
        Parent root = loader.load(getClass().getResourceAsStream("/UI.fxml"));

        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Lyrics App");
        primaryStage.show();
    }




    public static void main(String[] args) {
        launch();
    }
}
